// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.0
// source: plugin/command_context.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/** Plugin command context. */
export interface CommandContext {
  /** The name of the command. */
  name: string;
  /** Valid arguments for this command. */
  validArguments: string[];
  /** Valid subcommands for this command. */
  validSubcommands: string[];
  /** Arguments passed to the command. */
  arguments: { [key: string]: string };
  /** Optional nested subcommand context. */
  subcommand?: CommandContext | undefined;
}

export interface CommandContext_ArgumentsEntry {
  key: string;
  value: string;
}

function createBaseCommandContext(): CommandContext {
  return { name: "", validArguments: [], validSubcommands: [], arguments: {}, subcommand: undefined };
}

export const CommandContext: MessageFns<CommandContext> = {
  encode(message: CommandContext, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    for (const v of message.validArguments) {
      writer.uint32(18).string(v!);
    }
    for (const v of message.validSubcommands) {
      writer.uint32(26).string(v!);
    }
    Object.entries(message.arguments).forEach(([key, value]) => {
      CommandContext_ArgumentsEntry.encode({ key: key as any, value }, writer.uint32(34).fork()).join();
    });
    if (message.subcommand !== undefined) {
      CommandContext.encode(message.subcommand, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommandContext {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommandContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.validArguments.push(reader.string());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.validSubcommands.push(reader.string());
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          const entry4 = CommandContext_ArgumentsEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.arguments[entry4.key] = entry4.value;
          }
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.subcommand = CommandContext.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommandContext {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      validArguments: globalThis.Array.isArray(object?.validArguments)
        ? object.validArguments.map((e: any) => globalThis.String(e))
        : [],
      validSubcommands: globalThis.Array.isArray(object?.validSubcommands)
        ? object.validSubcommands.map((e: any) => globalThis.String(e))
        : [],
      arguments: isObject(object.arguments)
        ? Object.entries(object.arguments).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      subcommand: isSet(object.subcommand) ? CommandContext.fromJSON(object.subcommand) : undefined,
    };
  },

  toJSON(message: CommandContext): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.validArguments?.length) {
      obj.validArguments = message.validArguments;
    }
    if (message.validSubcommands?.length) {
      obj.validSubcommands = message.validSubcommands;
    }
    if (message.arguments) {
      const entries = Object.entries(message.arguments);
      if (entries.length > 0) {
        obj.arguments = {};
        entries.forEach(([k, v]) => {
          obj.arguments[k] = v;
        });
      }
    }
    if (message.subcommand !== undefined) {
      obj.subcommand = CommandContext.toJSON(message.subcommand);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommandContext>, I>>(base?: I): CommandContext {
    return CommandContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommandContext>, I>>(object: I): CommandContext {
    const message = createBaseCommandContext();
    message.name = object.name ?? "";
    message.validArguments = object.validArguments?.map((e) => e) || [];
    message.validSubcommands = object.validSubcommands?.map((e) => e) || [];
    message.arguments = Object.entries(object.arguments ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.subcommand = (object.subcommand !== undefined && object.subcommand !== null)
      ? CommandContext.fromPartial(object.subcommand)
      : undefined;
    return message;
  },
};

function createBaseCommandContext_ArgumentsEntry(): CommandContext_ArgumentsEntry {
  return { key: "", value: "" };
}

export const CommandContext_ArgumentsEntry: MessageFns<CommandContext_ArgumentsEntry> = {
  encode(message: CommandContext_ArgumentsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommandContext_ArgumentsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommandContext_ArgumentsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommandContext_ArgumentsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: CommandContext_ArgumentsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommandContext_ArgumentsEntry>, I>>(base?: I): CommandContext_ArgumentsEntry {
    return CommandContext_ArgumentsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommandContext_ArgumentsEntry>, I>>(
    object: I,
  ): CommandContext_ArgumentsEntry {
    const message = createBaseCommandContext_ArgumentsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string; value: unknown } ? { $case: T["$case"]; value?: DeepPartial<T["value"]> }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
