// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.0
//   protoc               v5.28.0

/* eslint-disable */

export * from "./database/results";
export * from "./database/prepared_statement";
